name: Translation Updates

on:
  workflow_dispatch:
  schedule:
  - cron: "0 21 * * 0"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: matomo-org/github-action-plugin-translations@master
      env:
        TransifexUsername: ${{ secrets.TransifexUsername }}
        TransifexPassword: ${{ secrets.TransifexPassword }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PluginName: "TagManager"
